wandb_version: 1

batch_size:
  value: 32
betas:
  value:
  - 0.99
  - 0.999
context_size:
  value: 32
dropout_proba:
  value: 0.4
lr:
  value: 0.05
num_components:
  value: 128
rnn_type:
  value: LSTM
tau_mean:
  value: 0.1
weight_decay:
  value: 0.01
