wandb_version: 1

batch_size:
  value: 128
betas:
  value:
  - 0.99
  - 0.99
context_size:
  value: 32
dropout_proba:
  value: 0.4
lr:
  value: 0.01
num_components:
  value: 64
rnn_type:
  value: LSTM
tau_mean:
  value: 0.05
weight_decay:
  value: 0.002
