wandb_version: 1

batch_size:
  value: 16
betas:
  value:
  - 0.9
  - 0.99
context_size:
  value: 32
dropout_proba:
  value: 0
lr:
  value: 0.02
num_components:
  value: 32
rnn_type:
  value: LSTM
tau_mean:
  value: 0.1
weight_decay:
  value: 0.01
