wandb_version: 1

batch_size:
  value: 16
betas:
  value:
  - 0.9
  - 0.999
context_size:
  value: 16
dropout_proba:
  value: 0
lr:
  value: 0.05
num_components:
  value: 8
rnn_type:
  value: LSTM
tau_mean:
  value: 1
weight_decay:
  value: 0
