wandb_version: 1

batch_size:
  value: 32
betas:
  value:
  - 0.99
  - 0.99
context_size:
  value: 8
dropout_proba:
  value: 0.3
lr:
  value: 0.01
num_components:
  value: 8
rnn_type:
  value: LSTM
tau_mean:
  value: 0.02
weight_decay:
  value: 0.02
