wandb_version: 1

batch_size:
  value: 64
betas:
  value:
  - 0.99
  - 0.999
context_size:
  value: 128
dropout_proba:
  value: 0.4
lr:
  value: 0.001
num_components:
  value: 16
rnn_type:
  value: LSTM
tau_mean:
  value: 0.2
weight_decay:
  value: 0.002
