wandb_version: 1

batch_size:
  value: 128
betas:
  value:
  - 0.99
  - 0.999
context_size:
  value: 8
dropout_proba:
  value: 0.3
lr:
  value: 0.005
num_components:
  value: 16
rnn_type:
  value: LSTM
tau_mean:
  value: 0.01
weight_decay:
  value: 0.002
