wandb_version: 1

batch_size:
  value: 128
betas:
  value:
  - 0.9
  - 0.99
context_size:
  value: 8
dropout_proba:
  value: 0
lr:
  value: 0.05
num_components:
  value: 128
rnn_type:
  value: LSTM
tau_mean:
  value: 0.1
weight_decay:
  value: 0.002
