wandb_version: 1

batch_size:
  value: 8
betas:
  value:
  - 0.9
  - 0.999
context_size:
  value: 128
dropout_proba:
  value: 0.3
lr:
  value: 0.001
num_components:
  value: 8
rnn_type:
  value: LSTM
weight_decay:
  value: 0.02
