wandb_version: 1

batch_size:
  value: 16
betas:
  value:
  - 0.9
  - 0.999
context_size:
  value: 64
dropout_proba:
  value: 0
lr:
  value: 0.05
num_components:
  value: 16
rnn_type:
  value: GRU
weight_decay:
  value: 0.01
