wandb_version: 1

batch_size:
  value: 64
betas:
  value:
  - 0.9
  - 0.999
context_size:
  value: 128
dropout_proba:
  value: 0.5
lr:
  value: 0.05
num_components:
  value: 64
rnn_type:
  value: LSTM
weight_decay:
  value: 0.02
