wandb_version: 1

batch_size:
  value: 8
betas:
  value:
  - 0.9
  - 0.999
context_size:
  value: 32
dropout_proba:
  value: 0.3
lr:
  value: 0.005
num_components:
  value: 16
rnn_type:
  value: GRU
weight_decay:
  value: 0.02
